/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tjframes;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Lopes
 */
public class jfGabriel extends javax.swing.JFrame {

    /**
     * Creates new form jfGabriel
     */
    public jfGabriel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpConverte = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbCalcDias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfIdade = new javax.swing.JTextPane();
        jlResultado = new javax.swing.JLabel();
        jtfResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtfValor = new javax.swing.JTextPane();
        jrbKm2Milhas = new javax.swing.JRadioButton();
        jrbMilhasParaKM = new javax.swing.JRadioButton();
        JBconverter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbEstCivil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jbEstCivil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora JojoFag");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setName("Calculadora Jojo"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCalcDias.setBackground(new java.awt.Color(51, 51, 255));
        jbCalcDias.setText("Calcular em Dias");
        jbCalcDias.setName("JBCalcDias"); // NOI18N
        jbCalcDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcDiasActionPerformed(evt);
            }
        });
        jPanel1.add(jbCalcDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Idade");
        jLabel1.setName("JTFIdade"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 51, 37, 24));

        jScrollPane1.setName(""); // NOI18N

        jtfIdade.setBackground(new java.awt.Color(255, 255, 255));
        jtfIdade.setName(""); // NOI18N
        jtfIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfIdadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdadeKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtfIdade);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 45, 118, 30));

        jlResultado.setBackground(new java.awt.Color(255, 255, 255));
        jlResultado.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        jlResultado.setForeground(new java.awt.Color(255, 255, 255));
        jlResultado.setText("Resultado:");
        jPanel1.add(jlResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 90, -1, -1));

        jtfResultado.setEditable(false);
        jtfResultado.setBackground(new java.awt.Color(255, 255, 255));
        jtfResultado.setName("jtfResultado"); // NOI18N
        jPanel1.add(jtfResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 87, 114, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 36, 40, 24));

        jtfValor.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jtfValor);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 36, 80, 30));

        jrbKm2Milhas.setBackground(new java.awt.Color(0, 0, 0));
        grpConverte.add(jrbKm2Milhas);
        jrbKm2Milhas.setForeground(new java.awt.Color(255, 255, 255));
        jrbKm2Milhas.setSelected(true);
        jrbKm2Milhas.setText("De Km Para Milhas");
        jPanel1.add(jrbKm2Milhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 68, -1, -1));

        jrbMilhasParaKM.setBackground(new java.awt.Color(0, 0, 0));
        grpConverte.add(jrbMilhasParaKM);
        jrbMilhasParaKM.setForeground(new java.awt.Color(255, 255, 255));
        jrbMilhasParaKM.setText("De Milhas Para Km");
        jrbMilhasParaKM.setName(""); // NOI18N
        jrbMilhasParaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMilhasParaKMActionPerformed(evt);
            }
        });
        jPanel1.add(jrbMilhasParaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 94, -1, -1));

        JBconverter.setBackground(new java.awt.Color(255, 28, 28));
        JBconverter.setText("Converter");
        JBconverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBconverterActionPerformed(evt);
            }
        });
        jPanel1.add(JBconverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 124, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Calculo De Idade Em Dias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Conversor de Milhas/km");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 12, 141, -1));

        jcbEstCivil.setBackground(new java.awt.Color(153, 153, 153));
        jcbEstCivil.setForeground(new java.awt.Color(255, 204, 51));
        jcbEstCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Amizade Colorida", " " }));
        jcbEstCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstCivilActionPerformed(evt);
            }
        });
        jPanel1.add(jcbEstCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado Cíivil");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 20));

        jbEstCivil.setForeground(new java.awt.Color(255, 255, 255));
        jbEstCivil.setText("Estado Civil?");
        jbEstCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstCivilActionPerformed(evt);
            }
        });
        jPanel1.add(jbEstCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBconverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBconverterActionPerformed
        // TODO add your handling code here:
        double result=0;
        double valor=Double.parseDouble(jtfValor.getText());
        if(jrbKm2Milhas.isSelected()){
            result=valor/1.6;
        }else if(jrbMilhasParaKM.isSelected()){
            result= valor*1.6;
        }        
        JOptionPane.showMessageDialog(this, "O Resultado é: "+result,"Conversão",JOptionPane.INFORMATION_MESSAGE );
       
    }//GEN-LAST:event_JBconverterActionPerformed

    private void jrbMilhasParaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMilhasParaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMilhasParaKMActionPerformed

    private void jtfIdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdadeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Somente Números");
        }
    }//GEN-LAST:event_jtfIdadeKeyTyped

    private void jtfIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jbCalcDias.doClick();
        }
    }//GEN-LAST:event_jtfIdadeKeyPressed

    private void jbCalcDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcDiasActionPerformed
        if (jtfIdade.getText().equals("")) {
            jtfResultado.setForeground(Color.red);
            jtfResultado.setText("Idade Vazia");

        } else {
            int idade = Integer.parseInt(jtfIdade.getText());
            int dias = idade * 365;

            if (dias >= 0) {
                jtfResultado.setForeground(Color.black);

            } else {
                jtfResultado.setForeground(Color.red);
            }
            jtfResultado.setText(Integer.toString(dias));
            jtfIdade.setText("");
            jtfResultado.requestFocus();
        } jtfResultado.requestFocus();

    }//GEN-LAST:event_jbCalcDiasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jcbEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstCivilActionPerformed

    private void jbEstCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstCivilActionPerformed
        // TODO add your handling code here:
        if(jcbEstCivil.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(this, "Nenhum estado Cívil Selecionado");
            
        }else
        JOptionPane.showMessageDialog(this, "Seu Estado cívil é: "+jcbEstCivil.getSelectedItem().toString());
    }//GEN-LAST:event_jbEstCivilActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfGabriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfGabriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfGabriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfGabriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfGabriel().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBconverter;
    private javax.swing.ButtonGroup grpConverte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCalcDias;
    private javax.swing.JButton jbEstCivil;
    private javax.swing.JComboBox<String> jcbEstCivil;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JRadioButton jrbKm2Milhas;
    private javax.swing.JRadioButton jrbMilhasParaKM;
    private javax.swing.JTextPane jtfIdade;
    private javax.swing.JTextField jtfResultado;
    private javax.swing.JTextPane jtfValor;
    // End of variables declaration//GEN-END:variables
}
